language: rust
cache: cargo

rust:
- 1.20.0
- stable

branches:
  only:
  - staging
  - trying
  - master

script:
- cargo test $FEATURES

env:
- FEATURES
- FEATURES="--features serde"
- FEATURES="--features parking_lot"