[package]
name = "simple-interner"
version = "0.1.0"
authors = ["Christopher Durham (CAD97) <cad97@cad97.com>"]

[dependencies]
serde = { version = "1", optional = true, features = ["derive"] }
parking_lot = { version = "0.5", optional = true }
