[package]
name = "simple-interner"
version = "0.1.0"
authors = ["Christopher Durham (CAD97) <cad97@cad97.com>"]

description = "A simple append-only interner"
repository = "https://github.com/CAD97/simple-interner"
readme = "Readme.md"
keywords = ["string interner", "interner", "cache"]
categories = ["caching", "parsing"]
license = "Apache-2.0 OR MIT"

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
serde = { version = "1", optional = true, features = ["derive"] }
parking_lot = { version = "0.5", optional = true }
